config/routes.rb
SitesCms::Application.routes.draw do
  ComfortableMexicanSofa::Routing.admin :path => '/admin'

  post 'contato/send_mail' => "contato#send_mail"

  ComfortableMexicanSofa::Routing.content :path => '/', :sitemap => false

end

app/models/message.rb
class Message
	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming


	attr_accessor :name, :site, :email, :content, :vindo_de

	validates_presence_of :name, :email, :content
	# validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
	validates_length_of :content, :maximum => 500

	def initialize(attributes = {})
		attributes.each do |name, value|
			send("#{name}=", value)
		end
	end

	def persisted?
		false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contato_controller.rb
class ContatoController < ApplicationController

	def index
		@message = Message.new
		render 'index'
	end

	def send_mail
		puts " >>>> 01"
		@message = Message.new(params[:message])
		@message.vindo_de = request.host
	 
		if @message.valid?
      		Contato.send_mail( @message ).deliver
      		flash[:notice] = "Sua mensagem foi enviada. Obrigado por entrar em contato."
      		#redirect_to :action => 'index'
      		redirect_to "/contato"
  		else
  			puts " >>>> ERRORS: #{ @message.errors.inspect }"
  			redirect_to "/contato"
  			flash[:error] = "Falha ao enviar mensagem."
  			#render :action => 'index'
  		end
  	end
  	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def mark_required(object, attribute)
		"*" if object.class.validators_on(attribute).map(&:class).include? ActiveModel::Validations::PresenceValidator
	end

	def flash_class(level)
		case level
		when :notice then "info"
		when :error then "error"
		when :alert then "warning"
		end
	end
	
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/views/contato/index.html.erb
 		 
<%= form_for(@message, :url => contato_send_mail_path, :html => {:class => "form-horizontal"}) do |f| %>

	<div class="control-group">
		<div class="controls">
			<% @message.errors.full_messages.each do |msg| %>
			<p><%= msg %></p>
			<% end %>
		</div>
	</div>


	<div class="control-group">
		<%= f.label :name, "Nome #{mark_required(@message, :name)}", :class => "control-label" %>
		<div class="controls">
			<%= f.text_field :name, :class => "input-xlarge"  %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :email, "E-mail #{mark_required(@message, :email)}", :class => "control-label"  %>
		<div class="controls">
			<%= f.text_field :email, :class => "input-xlarge"  %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :content, "Mensagem #{mark_required(@message, :content)}", :class => "control-label"  %>
		<div class="controls">
			<%= f.text_area :content, :rows => "5", :class => "input-block-level" %>
		</div>
	</div>

	<div class="control-group">
		<div class="controls">
			<%= f.submit "Enviar", :class => "btn btn-warning"%>
		</div>
	</div>

<% end %>

 

	 

app/views/layouts/_contato.html.erb
			

			<%= form_tag("/contato/send_mail", method: "post") do %>
			  
			
						<div class="span3">
									<fieldset>
										<div class="clearfix">
											<div class="input">
												<div class="input-prepend">
													<span class="add-on">Nome:</span>							
													<%= text_field(:message, :name, :size => "18") %>
												</div>
											</div>
										</div>

										<div class="clearfix">
											<div class="input">
												<div class="input-prepend">
													<span class="add-on">Email:</span>
													<%= text_field(:message, :email, :size => "25") %>
												</div>
											</div>
										</div>

										<div class="clearfix">
											<div class="input">
												<div class="input-prepend">
													<span class="add-on">Site &nbsp;&nbsp;:</span>
													<%= text_field(:message, :site, :size => "25") %>
												</div>
											</div>
										</div>
									</fieldset>									
								</div>
								<div class="span4">
									<fieldset>
										<div class="clearfix">
											<div class="input">
												<%= text_area(:message, :content, :rows => "8", :class => "input") %>
											 
											</div>
										</div>

										<div class="actions">
											<%= submit_tag("Enviar", :class => "btn btn-orange btn-red-pastel btn-steelblue btn-darkslategrey btn-large") %>
										</div>
									</fieldset>
								</div>


				<% end %>

app/views/layouts/_mensagens.html.erb
<% flash.each do |type, message| %>
	<div class='flash <%= type %>'><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SitesCms</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  sssss
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/zangraf.html.erb
 <!DOCTYPE html>
<html lang="pt-BR">
<head>

	<!-- start: Meta -->
	<meta charset="utf-8">
	<title><%= cms_page_content('title') %></title> 
	<meta content="Responsive portofolio at Bootstrap" name="description">
	<meta content="light, responsive, portofolio" name="keywords">
	<%= csrf_meta_tags %>
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
	<!-- end: Mobile Specific -->


  	<%= stylesheet_link_tag  "zangraf", media: "all", "data-turbolinks-track" => true %>
  
 
	<!-- start: favicon -->
	<link href="favicon.ico" rel="shortcut icon">
	<!-- end: favicon -->

    <!--[if IE 9]>
		<style></style>
	<![endif]-->    
    <!--[if IE 8]>
		<style>.nav-btn{display:none}.close-btn{display:none}.home-marker {top: 74px;}</style>
	<![endif]-->

</head>

<body>

<div id="outer-wrap">
	<div id="inner-wrap">


		<!--start: sidebar -->
		<div class="span2">
			<div id="top" class="sidebar-style sidebar-nav sidebar-nav-fixed">
				<div class="block logo">
					<!-- Logo -->
					<a class="block-title" href="index.html"><i class="logo-empresa"></i></a>

				</div>
				
				<div class="baseline-border">
					<div class="baseline">
						<p>Digital Fotolivro </p>
					</div>
				</div>

			    <nav id="nav" role="navigation">
			        <div class="block">
						<ul>
							<li class="is-active"><a href="/" class="home">Início</a></li>
							<li><a href="sobre" class="about">Sobre</a></li>
							<li><a href="galeria" class="portofolio">Galeria</a></li>
							<li><a href="contato" class="contact">Contato</a></li>
						</ul>
						<a class="close-btn" id="nav-close-btn" href="#top"><i class="icon-remove icon-2x icon-border"></i></a>
					</div>	
				</nav>		
				<div class="social">
					<a href="https://www.facebook.com/zangraf"><i class="icon-facebook"></i></a>
					<a href="#"><i class="icon-twitter"></i></a>
					<a href="#"><i class="icon-google-plus"></i></a>
					<a href="#"><i class="icon-pinterest-sign"></i></a>
				</div>
			</div>
		</div><!--end: sidebar -->

		<!--start: content -->
		<div class="content">				


			<%= yield %>	
 
 			
 			<div class="row">
			<div class="span12">
				
					<div class="text-right copyrigth">
					<a href="http://www.parseint.com.br" target="_blank" alt="Desenvolvimento Parseint.com.br">Desenvolvimento Parseint.com.br</a>
					</div>

			</div>
			</div>

		</div><!--end: content --> 

		<!-- start: back to top -->
		<div class="up">
			<a href="#" class="btn btn-large btn-orange btn-red-pastel btn-steelblue btn-darkslategrey">Back to top <i class="icon-chevron-up"></i></a>	
		</div>
		<!-- end: back to top -->

	</div> <!--end: inner-wrap -->
</div> <!--end: outer-wrap -->


	<!-- start: script -->

	<%= javascript_include_tag "zangraf", "data-turbolinks-track" => true %>
	<script src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>
  	<script src="/assets/gmap3.min.js"></script>
	<!-- end: script -->

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->	

	</body>

</html>

app/views/layouts/zangraf_contato.html.erb
 
	 

				<div class="span8 offset1 home-content-title">
					<h1>Zangraf - Digital Fotolivro</h1>
					<hr class="separador"/>
					<h2>Centro de Impressão Gráfica e Fotográfica de Formaturas</h2>
				</div>

				<div class="span9 offset1 home-content">
						<div class="project-slider">
						    <div class="callbacks_container">
						      <ul class="rslides" id="slider4">
						        <li>
						          <a href="#"><img src="assets/large/2.jpg" alt="content"></a>
						        </li>
						        <li>
						          <a href="#"><img src="assets/large/1.jpg" alt="content"></a>
						        </li>
						        <li>
						          <a href="#"><img src="assets/large/3.jpg" alt="content"></a>
						        </li>
						      </ul>
						    </div>
						</div>	
				</div>					

				<div class="span9 offset1 home-content">


					<div class="row home-features">
		                <div id="my-icon-1" class="span3">
							<div class="item">
		                        <div class="icon"><i class="icon-tablet icon-4x"></i></div>
		                        <h3>Responsive Layout</h3>
		                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce condimentum ullamcorper metus sit amet feugiat.</p>
							</div>
		                </div>
		                <div id="my-icon-2" class="span3">
		                	<div class="item">
		                        <div class="icon"><i class="icon-cogs icon-4x"></i></div>
		                        <h3>HTML5/CSS3 </h3>
		                        <p>Ut id leo lorem. Cras a aliquam felis. Vivamus risus enim, porttitor nec eleifend ut..</p>
		                    </div>    
		                </div>
		                <div id="my-icon-3" class="span3">
		                	<div class="item">
		                        <div class="icon"><i class="icon-beer icon-4x"></i></div>
		                        <h3>Easy to use</h3>
		                        <p>Donec nec orci varius lorem semper luctus posuere id est. Fusce tempus gravida est a..</p>
	                        </div>
		                </div>
            		</div>

				</div>